env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  'V3': true
  'M4x4': true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-undef: warn
